### ISSUE TITLE
Не устанавливается приложение 

### ISSUE THREAD

**Issue by itsreallyv1eds** [Moegram/Moegram#9]
Здравствуйте, у меня был клиент экстера икс, я зашёл, а тут поменяли название, я смотрю в чате, новый билд, устанавливаю, пишет ошибка, приложение не установлено, удаляю экстера икс, снова устанавливаю, не даёт, что делать

Xiaomi Mi 9 Lite
Android 12L
crDroid 8.4

Спасибо за ваш клиент

**Comment by Attorelle** [comment]
Blocked for off-topic.
